---

# create playbook to install mongodb in db-machine instance

- hosts: db
  gather_facts: yes
  become: true

  tasks:

  - name: Update
    command: sudo apt update -y

  - name: Upgrade
    command: sudo apt upgrade -y

# Install mongodb
  - name: Install Mongodb
    apt: pkg=mongodb state=present

# Ensure db is running
# Configure mongod.conf bind ip

  - name: Wait for MongoDB to start
    wait_for:
      host: localhost
      port: 27017
      state: started
      timeout: 300

  - name: Install sed
    apt:
      name: sed
      state: present

  - name: Configure mongodb.conf bind ip
    become: true
    shell: sudo sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mongodb.conf

  - name: Restart Mongodb
    service:
      name: mongodb
      state: restarted
      enabled: yes
