# Installing node

---
- hosts: web
  gather_facts: yes
  become: true

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: dist

    - name: Add DB_HOST environment variable to /etc/environment file
      lineinfile:
        path: /etc/environment
        line: 'export DB_HOST="mongodb://34.245.78.113:27017/posts"'
        state: present
        create: yes

    - name: Clone GitHub repository
      git:
        repo: https://github.com/ElenaCKay/tech241_aparta_app.git
        dest: /home/ubuntu/app
        version: main

    - name: Install Node.js
      get_url:
        url: https://deb.nodesource.com/setup_12.x
        dest: /tmp/node_setup.sh

    - name: Run Node.js setup script
      command: sudo -E bash /tmp/node_setup.sh

    - name: Install Node.js package
      apt:
        name: nodejs
        state: present

    - name: Run npm install
      npm:
        path: /home/ubuntu/app/app
        name: install

    - name: Seed database
      shell: node seeds/seed.js
      args:
        chdir: /home/ubuntu/app/app

    - name: Install sed
      apt:
        name: sed
        state: present

    - name: Configure reverse proxy in Nginx
      shell: sudo sed -i 's#try_files $uri $uri/ =404;#proxy_pass http://localhost:3000;#g' /etc/nginx/sites-available/default

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    - name: Install PM2 globally using npm
      npm:
        name: pm2
        global: yes
        state: present


    - name: Stop pm2 processes
      shell: pm2 kill

    - name: Start app with pm2
      shell: pm2 start app.js
      args:
        chdir: /home/ubuntu/app/app
